DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
    "MEMBER_NO" NUMBER NOT NULL,
    "MEMBER_ID"	VARCHAR2(50)		NOT NULL,
    "MEMBER_PW"	VARCHAR2(70)		NOT NULL,
    "MEMBER_NM"	VARCHAR2(20)		NOT NULL,
    "MEMBER_ADDR"	VARCHAR2(100)		NOT NULL,
    "MEMBER_FN"	VARCHAR2(20)		NOT NULL,
    "MEMBER_PHONE"	VARCHAR2(15)		NOT NULL,
    "MEMBER_GENDER"	VARCHAR2(3)		NOT NULL,
    "MEMBER_ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "MEMBER_TYPE"	VARCHAR2(100)		NOT NULL,
    "STATUS_CD"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '주소';

COMMENT ON COLUMN "MEMBER"."MEMBER_FN" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원 핸드폰 번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_ENROLL_DT" IS '회원 가입 날짜';

COMMENT ON COLUMN "MEMBER"."MEMBER_TYPE" IS '유형';

COMMENT ON COLUMN "MEMBER"."STATUS_CD" IS '회원 상태 코드';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
    "BOARD_NO"	NUMBER		NOT NULL,
    "BOARD_TITLE"	VARCHAR2(50)		NOT NULL,
    "BOARD_CONTENT"	CLOB		NOT NULL,
    "BOARD_CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "BOARD_MODIFY_DT"	DATE		NULL,
    "BOARD_READ_COUNT"	NUMBER		NOT NULL,
    "REPLY_CHECK_CD"	NUMBER		NOT NULL,
    "SCRAP_CHECK_CD"	NUMBER		NOT NULL,
    "BOARD_CATEGORY_CD"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER	DEFAULT NULL	NULL,
    "PROFESSION_NO"	NUMBER	DEFAULT NULL	NULL,
    "BOARD_STATUS_CD"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시판 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시판 내용';

COMMENT ON COLUMN "BOARD"."BOARD_CREATE_DT" IS '게시글 작성일자';

COMMENT ON COLUMN "BOARD"."BOARD_MODIFY_DT" IS '게시글 마지막 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."REPLY_CHECK_CD" IS '댓글 허용 비허용';

COMMENT ON COLUMN "BOARD"."SCRAP_CHECK_CD" IS '스크랩 허용 비허용';

COMMENT ON COLUMN "BOARD"."BOARD_CATEGORY_CD" IS '게시판 카테고리 코드';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "BOARD"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "BOARD"."BOARD_STATUS_CD" IS '게시판 상태 코드';

DROP TABLE "STATUS";

CREATE TABLE "STATUS" (
    "STATUS_CD"	NUMBER		NOT NULL,
    "STATUS_NM"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "STATUS"."STATUS_CD" IS '회원 상태 코드';

COMMENT ON COLUMN "STATUS"."STATUS_NM" IS '회원 상태 이름';

DROP TABLE "PROFESSION";

CREATE TABLE "PROFESSION" (
    "PROFESSION_NO"	NUMBER		NOT NULL,
    "PROFESSION_ID"	VARCHAR2(50)		NOT NULL,
    "PROFESSION_PW"	VARCHAR2(70)		NOT NULL,
    "PROFESSION_NM"	NVARCHAR2(5)		NOT NULL,
    "PROFESSION_PHONE"	VARCHAR2(15)		NOT NULL,
    "PROFESSION_ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "PROFESSION_GENDER"	VARCHAR2(3)		NOT NULL,
    "PROFESSION_PRICE"	VARCHAR2(20)		NOT NULL,
    "REMARKS"	VARCHAR2(1000)		NULL,
    "STATUS_CD"	NUMBER	DEFAULT 3	NOT NULL
);

COMMENT ON COLUMN "PROFESSION"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "PROFESSION"."PROFESSION_ID" IS '아이디(이메일)';

COMMENT ON COLUMN "PROFESSION"."PROFESSION_PW" IS '비밀번호';

COMMENT ON COLUMN "PROFESSION"."PROFESSION_NM" IS '이름';

COMMENT ON COLUMN "PROFESSION"."PROFESSION_PHONE" IS '핸드폰 번호';

COMMENT ON COLUMN "PROFESSION"."PROFESSION_ENROLL_DT" IS '가입일';

COMMENT ON COLUMN "PROFESSION"."PROFESSION_GENDER" IS '성별';

COMMENT ON COLUMN "PROFESSION"."PROFESSION_PRICE" IS '상담 가격';

COMMENT ON COLUMN "PROFESSION"."REMARKS" IS '관리자 등록';

COMMENT ON COLUMN "PROFESSION"."STATUS_CD" IS '전문가 상태 코드';

DROP TABLE "MUTE";

CREATE TABLE "MUTE" (
    "MUTE_NO"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MUTE"."MUTE_NO" IS '차단 대상 회원';

COMMENT ON COLUMN "MUTE"."MEMBER_NO" IS '회원 번호';

DROP TABLE "BOARD_CATEGORY";

CREATE TABLE "BOARD_CATEGORY" (
    "BOARD_CATEGORY_CD"	NUMBER		NOT NULL,
    "BOARD_CATEGORY_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_CATEGORY"."BOARD_CATEGORY_CD" IS '게시판 카테고리 코드';

COMMENT ON COLUMN "BOARD_CATEGORY"."BOARD_CATEGORY_NM" IS '게시판 카테고리 이름';

DROP TABLE "RESERVATION";

CREATE TABLE "RESERVATION" (
    "RESERVATION_NO"	NUMBER		NOT NULL,
    "RESERVATION_ENROLL_DT"	DATE		NOT NULL,
    "RESERVATION_ENROLL_TIME"	VARCHAR2(20)		NOT NULL,
    "RESERVATION_STATUS_CD"	NUMBER		NULL,
    "RESERVATION_CANCEL"	VARCHAR2(2000)		NULL,
    "PROFESSION_NO"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER		NOT NULL,
    "COUNSEL_CATEGORY_NO"	NUMBER		NOT NULL,
    "RESERVATION_PAY_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "RESERVATION"."RESERVATION_NO" IS '상담 예약 번호';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_ENROLL_DT" IS '상담일';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_ENROLL_TIME" IS '상담 예약 시간';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_STATUS_CD" IS '상담 예약 상태';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_CANCEL" IS '상담 취소 사유';

COMMENT ON COLUMN "RESERVATION"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "RESERVATION"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "RESERVATION"."COUNSEL_CATEGORY_NO" IS '상담 방법 카테고리 번호';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_PAY_NO" IS '상담 예약 결제 번호';

DROP TABLE "REPLY";

CREATE TABLE "REPLY" (
    "REPLY_NO"	NUMBER		NOT NULL,
    "REPLY_CONTENT"	NVARCHAR2(2000)		NOT NULL,
    "REPLY_CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "REPLY_MODIFY_DT"	DATE		NULL,
    "REPLY_STATUS_CD"	NUMBER		NOT NULL,
    "REPLY_NESTED_CD"	NUMBER		NOT NULL,
    "BOARD_NO"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER	DEFAULT NULL	NULL,
    "PROFESSION_NO"	NUMBER	DEFAULT NULL	NULL,
    "PARENT_REPLY_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글 번호';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DT" IS '댓글 작성일';

COMMENT ON COLUMN "REPLY"."REPLY_MODIFY_DT" IS '댓글 마지막 수정 날짜';

COMMENT ON COLUMN "REPLY"."REPLY_STATUS_CD" IS '댓글 상태 코드';

COMMENT ON COLUMN "REPLY"."REPLY_NESTED_CD" IS '대댓글 상태 코드';

COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "REPLY"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "REPLY"."PARENT_REPLY_NO" IS '부모 댓글 번호';

DROP TABLE "CHATTING";

CREATE TABLE "CHATTING" (
    "CHATTING_NO"	NUMBER		NOT NULL,
    "CHATTING_ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "CHATTING_STATUS_CD"	NUMBER	DEFAULT 1	NOT NULL,
    "RESERVATION_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATTING"."CHATTING_NO" IS '채팅 번호';

COMMENT ON COLUMN "CHATTING"."CHATTING_ENROLL_DT" IS '상담 시작시간';

COMMENT ON COLUMN "CHATTING"."CHATTING_STATUS_CD" IS '사용가능여부';

COMMENT ON COLUMN "CHATTING"."RESERVATION_NO" IS '상담 예약 번호';

DROP TABLE "EMPATHY";

CREATE TABLE "EMPATHY" (
    "MEMBER_NO"	NUMBER		NOT NULL,
    "BOARD_NO"	NUMBER		NOT NULL,
    "EMPATHY_STATUS_CD"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "EMPATHY"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "EMPATHY"."BOARD_NO" IS '게시판 번호';

COMMENT ON COLUMN "EMPATHY"."EMPATHY_STATUS_CD" IS '공감 코드';

DROP TABLE "PROFESSION_WISH";

CREATE TABLE "PROFESSION_WISH" (
    "MEMBER_NO"	NUMBER		NOT NULL,
    "PROFESSION_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PROFESSION_WISH"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "PROFESSION_WISH"."PROFESSION_NO" IS '전문가 번호';

DROP TABLE "REPORT";

CREATE TABLE "REPORT" (
    "REPORT_NO"	NUMBER		NOT NULL,
    "REPORT_CONTENT"	VARCHAR2(1000)		NOT NULL,
    "REPORT_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "MEMBER_NO"	NUMBER		NOT NULL,
    "BOARD_NO"	NUMBER		NULL,
    "REPLY_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고 번호';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고 내용';

COMMENT ON COLUMN "REPORT"."REPORT_DT" IS '신고 시간';

COMMENT ON COLUMN "REPORT"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "REPORT"."BOARD_NO" IS '게시판 번호';

COMMENT ON COLUMN "REPORT"."REPLY_NO" IS '댓글 번호';

DROP TABLE "REVIEW";

CREATE TABLE "REVIEW" (
    "REVIEW_NO"	NUMBER		NOT NULL,
    "REVIEW_CONTENT"	VARCHAR2(1000)		NOT NULL,
    "REVIEW_STARPOINT"	NUMBER		NOT NULL,
    "PROFESSION_NO"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_NO" IS '상담사 후기 번호';

COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENT" IS '상담수 후기 내용';

COMMENT ON COLUMN "REVIEW"."REVIEW_STARPOINT" IS '후기 별점';

COMMENT ON COLUMN "REVIEW"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "REVIEW"."MEMBER_NO" IS '회원 번호';

DROP TABLE "LETTER";

CREATE TABLE "LETTER" (
    "LETTER_NO"	NUMBER		NOT NULL,
    "LETTER_CONTENT"	VARCHAR2(2000)		NOT NULL,
    "LETTER_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "LETTER_READ"	NUMBER		NOT NULL,
    "LETTER_TYPE"	NUMBER	DEFAULT 1	NOT NULL,
    "LETTER_STATUS_CD"	NUMBER	DEFAULT 0	NOT NULL,
    "MEMBER_NO"	NUMBER	DEFAULT NULL	NULL,
    "PROFESSION_NO"	NUMBER	DEFAULT NULL	NULL,
    "LETTER_REPLY"	NUMBER	DEFAULT NULL	NULL
);

COMMENT ON COLUMN "LETTER"."LETTER_NO" IS '쪽지 고유 번호';

COMMENT ON COLUMN "LETTER"."LETTER_CONTENT" IS '쪽지 내용';

COMMENT ON COLUMN "LETTER"."LETTER_DT" IS '쪽지를 보낸 시간';

COMMENT ON COLUMN "LETTER"."LETTER_READ" IS 'reading';

COMMENT ON COLUMN "LETTER"."LETTER_TYPE" IS '구분';

COMMENT ON COLUMN "LETTER"."LETTER_STATUS_CD" IS '상태코드';

COMMENT ON COLUMN "LETTER"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "LETTER"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "LETTER"."LETTER_REPLY" IS '쪽지 답변 번호';

DROP TABLE "EMOTION_DIARY";

CREATE TABLE "EMOTION_DIARY" (
    "EMOTION_NO"	NUMBER		NOT NULL,
    "EMOTION_CONTENT"	VARCHAR2(1000)		NOT NULL,
    "EMOTION_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "MEMBER_NO"	NUMBER		NOT NULL,
    "EMOTION_CATEGORY_CD"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_NO" IS '증상기록 번호';

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_CONTENT" IS '증상기록 메모';

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_DT" IS '증상 기록 시간';

COMMENT ON COLUMN "EMOTION_DIARY"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_CATEGORY_CD" IS '증상 기록 코드';

DROP TABLE "EMOTION_DIARY_CATEGORY";

CREATE TABLE "EMOTION_DIARY_CATEGORY" (
    "EMOTION_CATEGORY_CD"	NUMBER		NOT NULL,
    "EMOTION_CATEGORY_NM"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "EMOTION_DIARY_CATEGORY"."EMOTION_CATEGORY_CD" IS '증상 기록 코드';

COMMENT ON COLUMN "EMOTION_DIARY_CATEGORY"."EMOTION_CATEGORY_NM" IS '증상 기록 명';

DROP TABLE "IMAGE";

CREATE TABLE "IMAGE" (
    "IMAGE_NO"	NUMBER		NOT NULL,
    "IMAGE_PATH"	VARCHAR2(200)		NOT NULL,
    "IMAGE_NM"	VARCHAR2(30)		NOT NULL,
    "IMAGE_ORIGINAL"	VARCHAR2(100)		NOT NULL,
    "IMAGE_LEVEL"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER	DEFAULT NULL	NULL,
    "PROFESSION_NO"	NUMBER	DEFAULT NULL	NULL,
    "BOARD_NO"	NUMBER	DEFAULT NULL	NULL
);

COMMENT ON COLUMN "IMAGE"."IMAGE_NO" IS '이미지 번호';

COMMENT ON COLUMN "IMAGE"."IMAGE_PATH" IS '이미지 경로';

COMMENT ON COLUMN "IMAGE"."IMAGE_NM" IS '이미지 명';

COMMENT ON COLUMN "IMAGE"."IMAGE_ORIGINAL" IS '원본 이미지 명';

COMMENT ON COLUMN "IMAGE"."IMAGE_LEVEL" IS '이미지 레벨';

COMMENT ON COLUMN "IMAGE"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "IMAGE"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "IMAGE"."BOARD_NO" IS '게시판 번호';

DROP TABLE "PAYMENT";

CREATE TABLE "PAYMENT" (
    "PAY_NO"	NUMBER		NOT NULL,
    "PAY_AMOUNT"	VARCHAR2(30)		NOT NULL,
    "PAY_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
    "PAY_UPDATE_DT"	DATE		NULL,
    "PAYMENT_STATUS"	NUMBER		NOT NULL,
    "PAY_OPTION_NO"	NUMBER		NOT NULL,
    "RESERVATION_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."PAY_NO" IS '결제번호';

COMMENT ON COLUMN "PAYMENT"."PAY_AMOUNT" IS '최종결제금액';

COMMENT ON COLUMN "PAYMENT"."PAY_DT" IS '결제 완료 시간';

COMMENT ON COLUMN "PAYMENT"."PAY_UPDATE_DT" IS '결제 수정 시간';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_STATUS" IS '결제완료/취소';

COMMENT ON COLUMN "PAYMENT"."PAY_OPTION_NO" IS '결제 수단 코드';

COMMENT ON COLUMN "PAYMENT"."RESERVATION_NO" IS '상담 예약 번호';

DROP TABLE "PAY_OPTION";

CREATE TABLE "PAY_OPTION" (
    "PAY_OPTION_NO"	NUMBER		NOT NULL,
    "PAY_OPTION_NM"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "PAY_OPTION"."PAY_OPTION_NO" IS '결제 수단 코드';

COMMENT ON COLUMN "PAY_OPTION"."PAY_OPTION_NM" IS '결제 수단 명';

DROP TABLE "BOARD_STATUS";

CREATE TABLE "BOARD_STATUS" (
    "BOARD_STATUS_CD"	NUMBER		NOT NULL,
    "BOARD_STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_STATUS"."BOARD_STATUS_CD" IS '게시판 상태 코드';

COMMENT ON COLUMN "BOARD_STATUS"."BOARD_STATUS_NM" IS '게시글 상태 이름';

DROP TABLE "SELF_CHECK_QUESTION";

CREATE TABLE "SELF_CHECK_QUESTION" (
    "QUESTION_NO"	NUMBER		NOT NULL,
    "CATEGORY_NO"	NUMBER		NOT NULL,
    "QUESTION_CONTENT"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "SELF_CHECK_QUESTION"."QUESTION_NO" IS '질문번호';

COMMENT ON COLUMN "SELF_CHECK_QUESTION"."CATEGORY_NO" IS '증상 카테고리 번호';

COMMENT ON COLUMN "SELF_CHECK_QUESTION"."QUESTION_CONTENT" IS '질문내용';

DROP TABLE "SELF_CHECK_CATEGORY";

CREATE TABLE "SELF_CHECK_CATEGORY" (
    "CATEGORY_NO"	NUMBER		NOT NULL,
    "CATEGORY_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "SELF_CHECK_CATEGORY"."CATEGORY_NO" IS '증상 카테고리 번호';

COMMENT ON COLUMN "SELF_CHECK_CATEGORY"."CATEGORY_NM" IS '증상명';

DROP TABLE "SELF_CHECK_ANSWER";

CREATE TABLE "SELF_CHECK_ANSWER" (
    "ANSWER_NO"	NUMBER		NOT NULL,
    "ANSWER_TYPE"	NUMBER		NOT NULL,
    "ANSWER_CONTENT"	VARCHAR2(200)		NOT NULL,
    "QUESTION_NO"	NUMBER		NOT NULL,
    "CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SELF_CHECK_ANSWER"."ANSWER_NO" IS '증상 답변 번호';

COMMENT ON COLUMN "SELF_CHECK_ANSWER"."ANSWER_TYPE" IS '증상 답변 종류';

COMMENT ON COLUMN "SELF_CHECK_ANSWER"."ANSWER_CONTENT" IS '중상 답변 내용';

COMMENT ON COLUMN "SELF_CHECK_ANSWER"."QUESTION_NO" IS '질문번호';

COMMENT ON COLUMN "SELF_CHECK_ANSWER"."CATEGORY_NO" IS '증상 카테고리 번호';

DROP TABLE "EMPATHY_STATUS";

CREATE TABLE "EMPATHY_STATUS" (
    "EMPATHY_STATUS_CD"	NUMBER		NOT NULL,
    "EMPATHY_STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "EMPATHY_STATUS"."EMPATHY_STATUS_CD" IS '공감 코드';

COMMENT ON COLUMN "EMPATHY_STATUS"."EMPATHY_STATUS_NM" IS '공감 명';

DROP TABLE "COUNSEL_CATEGORY";

CREATE TABLE "COUNSEL_CATEGORY" (
    "COUNSEL_CATEGORY_NO"	NUMBER		NOT NULL,
    "COUNSEL_CATEGORY_NM"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "COUNSEL_CATEGORY"."COUNSEL_CATEGORY_NO" IS '상담 방법 카테고리 번호';

COMMENT ON COLUMN "COUNSEL_CATEGORY"."COUNSEL_CATEGORY_NM" IS '상담 방법 카테고리 명';

DROP TABLE "NOTICE";

CREATE TABLE "NOTICE" (
"NOTICE_NO"	NUMBER		NOT NULL,
"MEMBER_NO"	NUMBER		NOT NULL,
"NOTICE_CONTENT"	VARCHAR2(1000)		NOT NULL,
"NOTICE_STATUS_CD"	NUMBER	DEFAULT 1	NOT NULL,
"BOARD_NO"	NUMBER		NULL,
"LETTER_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '알림번호';

COMMENT ON COLUMN "NOTICE"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '알림내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_STATUS_CD" IS '알림상태';

COMMENT ON COLUMN "NOTICE"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "NOTICE"."LETTER_NO" IS '쪽지 고유 번호';

DROP TABLE "SELF_CHECK_RESULT";

CREATE TABLE "SELF_CHECK_RESULT" (
    "RESULT_NO"	NUMBER		NOT NULL,
    "CATEGORY_NO"	NUMBER		NOT NULL,
    "RESULT_CONTENT"	VARCHAR2(1000)		NOT NULL,
    "RESULT_RATE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SELF_CHECK_RESULT"."RESULT_NO" IS '증상 결과 번호';

COMMENT ON COLUMN "SELF_CHECK_RESULT"."CATEGORY_NO" IS '증상 카테고리 번호';

COMMENT ON COLUMN "SELF_CHECK_RESULT"."RESULT_CONTENT" IS '증상 결과 내용';

COMMENT ON COLUMN "SELF_CHECK_RESULT"."RESULT_RATE" IS '증상 결과 구분';

DROP TABLE "PROFESSION_HOSPITAL";

CREATE TABLE "PROFESSION_HOSPITAL" (
    "PROFESSION_NO"	NUMBER		NOT NULL,
    "HOSPITAL_NM"	VARCHAR2(50)		NOT NULL,
    "HOSPITAL_ADDR"	VARCHAR2(200)		NOT NULL,
    "HOSPITAL_PHONE"	VARCHAR2(20)		NOT NULL,
    "BUSINESS_NO"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "PROFESSION_HOSPITAL"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "PROFESSION_HOSPITAL"."HOSPITAL_NM" IS '병원명';

COMMENT ON COLUMN "PROFESSION_HOSPITAL"."HOSPITAL_ADDR" IS '병원 주소';

COMMENT ON COLUMN "PROFESSION_HOSPITAL"."HOSPITAL_PHONE" IS '병원 전화번호';

COMMENT ON COLUMN "PROFESSION_HOSPITAL"."BUSINESS_NO" IS '병원 번호';

DROP TABLE "PROFESSION_INFORMATION";

CREATE TABLE "PROFESSION_INFORMATION" (
    "PROFESSION_NO"	NUMBER		NOT NULL,
    "PROFESSION_UNIVERSITY"	VARCHAR2(50)		NULL,
    "PROFESSION_DEPARTMENT"	VARCHAR2(50)		NULL,
    "PROFESSION_MAJOR"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "PROFESSION_INFORMATION"."PROFESSION_NO" IS '전문가 번호';

COMMENT ON COLUMN "PROFESSION_INFORMATION"."PROFESSION_UNIVERSITY" IS '학교명';

COMMENT ON COLUMN "PROFESSION_INFORMATION"."PROFESSION_DEPARTMENT" IS '학과명';

COMMENT ON COLUMN "PROFESSION_INFORMATION"."PROFESSION_MAJOR" IS '전공';

DROP TABLE "MEMBER_SELF_CHECK";

CREATE TABLE "MEMBER_SELF_CHECK" (
    "MEMBER_NO"	NUMBER		NOT NULL,
    "RESULT_NO"	NUMBER		NOT NULL,
    "CATEGORY_NO"	NUMBER		NOT NULL,
    "Field"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "MEMBER_SELF_CHECK"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "MEMBER_SELF_CHECK"."RESULT_NO" IS '증상 결과 번호';

COMMENT ON COLUMN "MEMBER_SELF_CHECK"."CATEGORY_NO" IS '증상 카테고리 번호';

DROP TABLE "MANAGER";

CREATE TABLE "MANAGER" (
    "MANAGER_NO"	NUMBER		NOT NULL,
    "MANAGER_ID"	VARCHAR2(30)		NOT NULL,
    "MANAGER_PW"	VARCHAR2(50)		NOT NULL,
    "MANAGER_NM"	VARCHAR2(10)		NOT NULL,
    "MANAGER_GRADE_NO"	NUMBER	DEFAULT 1	NOT NULL,
    "GRADE_NO2"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MANAGER"."MANAGER_NO" IS '관리자번호';

COMMENT ON COLUMN "MANAGER"."MANAGER_ID" IS '관리자 아이디';

COMMENT ON COLUMN "MANAGER"."MANAGER_PW" IS '관리자 비밀번호';

COMMENT ON COLUMN "MANAGER"."MANAGER_NM" IS '관리자 이름';

COMMENT ON COLUMN "MANAGER"."MANAGER_GRADE_NO" IS '관리자 등급';

COMMENT ON COLUMN "MANAGER"."GRADE_NO2" IS '등급번호';

DROP TABLE "MANAGER_GRADE";

CREATE TABLE "MANAGER_GRADE" (
    "GRADE_NO"	NUMBER		NOT NULL,
    "GRADE_NM"	VARCHAR2(10)	DEFAULT 일반	NOT NULL
);

COMMENT ON COLUMN "MANAGER_GRADE"."GRADE_NO" IS '등급번호';

COMMENT ON COLUMN "MANAGER_GRADE"."GRADE_NM" IS '등급명';

DROP TABLE "RESERVATION_PAYMENT";

CREATE TABLE "RESERVATION_PAYMENT" (
    "RESERVATION_PAY_NO"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER		NOT NULL,
    "PROFESSION_NO"	NUMBER		NOT NULL,
    "TOTAL_CNT"	NUMBER	DEFAULT 1	NOT NULL,
    "USED_CNT"	NUMBER	DEFAULT 1	NOT NULL,
    "STATUS_CD"	NUMBER	DEFAULT 1	NOT NULL,
    "PAY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESERVATION_PAYMENT"."RESERVATION_PAY_NO" IS '상담예약 결제 번호';

COMMENT ON COLUMN "RESERVATION_PAYMENT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "RESERVATION_PAYMENT"."PROFESSION_NO" IS '전문가번호';

COMMENT ON COLUMN "RESERVATION_PAYMENT"."TOTAL_CNT" IS '상담가능횟수';

COMMENT ON COLUMN "RESERVATION_PAYMENT"."USED_CNT" IS '상담 사용수';

COMMENT ON COLUMN "RESERVATION_PAYMENT"."STATUS_CD" IS '사용가능여부';

COMMENT ON COLUMN "RESERVATION_PAYMENT"."PAY_NO" IS '결제번호';

DROP TABLE "CHATTING_MESSAGE";

CREATE TABLE "CHATTING_MESSAGE" (
    "CHAT_NO"	NUMBER		NOT NULL,
    "MESSAGE"	VARCHAR2(4000)		NULL,
    "CREATE_DT"	DATE	DEFAULT SYSDATE	NULL,
    "PROFESSION_NO"	NUMBER		NOT NULL,
    "MEMBER_NO"	NUMBER		NOT NULL,
    "CHATTING_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATTING_MESSAGE"."CHAT_NO" IS '채팅번호';

COMMENT ON COLUMN "CHATTING_MESSAGE"."MESSAGE" IS '내용';

COMMENT ON COLUMN "CHATTING_MESSAGE"."CREATE_DT" IS '작성시간';

COMMENT ON COLUMN "CHATTING_MESSAGE"."PROFESSION_NO" IS '전문가번호';

COMMENT ON COLUMN "CHATTING_MESSAGE"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "CHATTING_MESSAGE"."CHATTING_NO" IS '채팅 번호';

DROP TABLE "CHAT_FILE";

CREATE TABLE "CHAT_FILE" (
    "CHAT_FILE_NO"	NUMBER		NOT NULL,
    "FILE_PATH"	VARCHAR2(50)		NOT NULL,
    "FILE_NAME"	VARCHAR2(50)		NOT NULL,
    "CHATTING_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHAT_FILE"."CHAT_FILE_NO" IS '파일번호';

COMMENT ON COLUMN "CHAT_FILE"."FILE_PATH" IS '파일경로';

COMMENT ON COLUMN "CHAT_FILE"."FILE_NAME" IS '파일명';

COMMENT ON COLUMN "CHAT_FILE"."CHATTING_NO" IS '채팅 번호';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
    "MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
    "BOARD_NO"
);

ALTER TABLE "STATUS" ADD CONSTRAINT "PK_STATUS" PRIMARY KEY (
    "STATUS_CD"
);

ALTER TABLE "PROFESSION" ADD CONSTRAINT "PK_PROFESSION" PRIMARY KEY (
    "PROFESSION_NO"
);

ALTER TABLE "MUTE" ADD CONSTRAINT "PK_MUTE" PRIMARY KEY (
    "MUTE_NO",
    "MEMBER_NO"
);

ALTER TABLE "BOARD_CATEGORY" ADD CONSTRAINT "PK_BOARD_CATEGORY" PRIMARY KEY (
    "BOARD_CATEGORY_CD"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY (
    "RESERVATION_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
    "REPLY_NO"
);

ALTER TABLE "CHATTING" ADD CONSTRAINT "PK_CHATTING" PRIMARY KEY (
    "CHATTING_NO"
);

ALTER TABLE "EMPATHY" ADD CONSTRAINT "PK_EMPATHY" PRIMARY KEY (
    "MEMBER_NO",
    "BOARD_NO"
);

ALTER TABLE "PROFESSION_WISH" ADD CONSTRAINT "PK_PROFESSION_WISH" PRIMARY KEY (
    "MEMBER_NO",
    "PROFESSION_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
    "REPORT_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
    "REVIEW_NO"
);

ALTER TABLE "LETTER" ADD CONSTRAINT "PK_LETTER" PRIMARY KEY (
    "LETTER_NO"
);

ALTER TABLE "EMOTION_DIARY" ADD CONSTRAINT "PK_EMOTION_DIARY" PRIMARY KEY (
    "EMOTION_NO"
);

ALTER TABLE "EMOTION_DIARY_CATEGORY" ADD CONSTRAINT "PK_EMOTION_DIARY_CATEGORY" PRIMARY KEY (
    "EMOTION_CATEGORY_CD"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "PK_IMAGE" PRIMARY KEY (
    "IMAGE_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
    "PAY_NO"
);

ALTER TABLE "PAY_OPTION" ADD CONSTRAINT "PK_PAY_OPTION" PRIMARY KEY (
    "PAY_OPTION_NO"
);

ALTER TABLE "BOARD_STATUS" ADD CONSTRAINT "PK_BOARD_STATUS" PRIMARY KEY (
    "BOARD_STATUS_CD"
);

ALTER TABLE "SELF_CHECK_QUESTION" ADD CONSTRAINT "PK_SELF_CHECK_QUESTION" PRIMARY KEY (
    "QUESTION_NO",
    "CATEGORY_NO"
);

ALTER TABLE "SELF_CHECK_CATEGORY" ADD CONSTRAINT "PK_SELF_CHECK_CATEGORY" PRIMARY KEY (
    "CATEGORY_NO"
);

ALTER TABLE "SELF_CHECK_ANSWER" ADD CONSTRAINT "PK_SELF_CHECK_ANSWER" PRIMARY KEY (
    "ANSWER_NO",
    "ANSWER_TYPE"
);

ALTER TABLE "EMPATHY_STATUS" ADD CONSTRAINT "PK_EMPATHY_STATUS" PRIMARY KEY (
    "EMPATHY_STATUS_CD"
);

ALTER TABLE "COUNSEL_CATEGORY" ADD CONSTRAINT "PK_COUNSEL_CATEGORY" PRIMARY KEY (
    "COUNSEL_CATEGORY_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
    "NOTICE_NO",
    "MEMBER_NO"
);

ALTER TABLE "SELF_CHECK_RESULT" ADD CONSTRAINT "PK_SELF_CHECK_RESULT" PRIMARY KEY (
    "RESULT_NO",
    "CATEGORY_NO"
);

ALTER TABLE "PROFESSION_HOSPITAL" ADD CONSTRAINT "PK_PROFESSION_HOSPITAL" PRIMARY KEY (
    "PROFESSION_NO"
);

ALTER TABLE "PROFESSION_INFORMATION" ADD CONSTRAINT "PK_PROFESSION_INFORMATION" PRIMARY KEY (
    "PROFESSION_NO"
);

ALTER TABLE "MEMBER_SELF_CHECK" ADD CONSTRAINT "PK_MEMBER_SELF_CHECK" PRIMARY KEY (
    "MEMBER_NO",
    "RESULT_NO",
    "CATEGORY_NO"
);

ALTER TABLE "MANAGER" ADD CONSTRAINT "PK_MANAGER" PRIMARY KEY (
    "MANAGER_NO"
);

ALTER TABLE "MANAGER_GRADE" ADD CONSTRAINT "PK_MANAGER_GRADE" PRIMARY KEY (
    "GRADE_NO"
);

ALTER TABLE "RESERVATION_PAYMENT" ADD CONSTRAINT "PK_RESERVATION_PAYMENT" PRIMARY KEY (
    "RESERVATION_PAY_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "PK_CHATTING_MESSAGE" PRIMARY KEY (
    "CHAT_NO"
);

ALTER TABLE "CHAT_FILE" ADD CONSTRAINT "PK_CHAT_FILE" PRIMARY KEY (
    "CHAT_FILE_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_STATUS_TO_MEMBER_1" FOREIGN KEY (
    "STATUS_CD"
)
REFERENCES "STATUS" (
    "STATUS_CD"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_CATEGORY_TO_BOARD_1" FOREIGN KEY (
    "BOARD_CATEGORY_CD"
)
REFERENCES "BOARD_CATEGORY" (
    "BOARD_CATEGORY_CD"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_PROFESSION_TO_BOARD_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_STATUS_TO_BOARD_1" FOREIGN KEY (
    "BOARD_STATUS_CD"
)
REFERENCES "BOARD_STATUS" (
    "BOARD_STATUS_CD"
);

ALTER TABLE "PROFESSION" ADD CONSTRAINT "FK_STATUS_TO_PROFESSION_1" FOREIGN KEY (
    "STATUS_CD"
)
REFERENCES "STATUS" (
    "STATUS_CD"
);

ALTER TABLE "MUTE" ADD CONSTRAINT "FK_MEMBER_TO_MUTE_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_PROFESSION_TO_RESERVATION_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_MEMBER_TO_RESERVATION_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_COUNSEL_CATEGORY_TO_RESERVATION_1" FOREIGN KEY (
    "COUNSEL_CATEGORY_NO"
)
REFERENCES "COUNSEL_CATEGORY" (
    "COUNSEL_CATEGORY_NO"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_RESERVATION_PAYMENT_TO_RESERVATION_1" FOREIGN KEY (
    "RESERVATION_PAY_NO"
)
REFERENCES "RESERVATION_PAYMENT" (
    "RESERVATION_PAY_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_TO_REPLY_1" FOREIGN KEY (
    "BOARD_NO"
)
REFERENCES "BOARD" (
    "BOARD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_PROFESSION_TO_REPLY_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_REPLY_TO_REPLY_1" FOREIGN KEY (
    "PARENT_REPLY_NO"
)
REFERENCES "REPLY" (
    "REPLY_NO"
);

ALTER TABLE "CHATTING" ADD CONSTRAINT "FK_RESERVATION_TO_CHATTING_1" FOREIGN KEY (
    "RESERVATION_NO"
)
REFERENCES "RESERVATION" (
    "RESERVATION_NO"
);

ALTER TABLE "EMPATHY" ADD CONSTRAINT "FK_MEMBER_TO_EMPATHY_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "EMPATHY" ADD CONSTRAINT "FK_BOARD_TO_EMPATHY_1" FOREIGN KEY (
    "BOARD_NO"
)
REFERENCES "BOARD" (
    "BOARD_NO"
);

ALTER TABLE "EMPATHY" ADD CONSTRAINT "FK_EMPATHY_STATUS_TO_EMPATHY_1" FOREIGN KEY (
    "EMPATHY_STATUS_CD"
)
REFERENCES "EMPATHY_STATUS" (
    "EMPATHY_STATUS_CD"
);

ALTER TABLE "PROFESSION_WISH" ADD CONSTRAINT "FK_MEMBER_TO_PROFESSION_WISH_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "PROFESSION_WISH" ADD CONSTRAINT "FK_PROFESSION_TO_PROFESSION_WISH_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_BOARD_TO_REPORT_1" FOREIGN KEY (
    "BOARD_NO"
)
REFERENCES "BOARD" (
    "BOARD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_REPLY_TO_REPORT_1" FOREIGN KEY (
    "REPLY_NO"
)
REFERENCES "REPLY" (
    "REPLY_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_PROFESSION_TO_REVIEW_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "LETTER" ADD CONSTRAINT "FK_MEMBER_TO_LETTER_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "LETTER" ADD CONSTRAINT "FK_PROFESSION_TO_LETTER_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "LETTER" ADD CONSTRAINT "FK_LETTER_TO_LETTER_1" FOREIGN KEY (
    "LETTER_REPLY"
)
REFERENCES "LETTER" (
    "LETTER_NO"
);

ALTER TABLE "EMOTION_DIARY" ADD CONSTRAINT "FK_MEMBER_TO_EMOTION_DIARY_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "EMOTION_DIARY" ADD CONSTRAINT "FK_EMOTION_DIARY_CATEGORY_TO_EMOTION_DIARY_1" FOREIGN KEY (
    "EMOTION_CATEGORY_CD"
)
REFERENCES "EMOTION_DIARY_CATEGORY" (
    "EMOTION_CATEGORY_CD"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "FK_MEMBER_TO_IMAGE_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "FK_PROFESSION_TO_IMAGE_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "FK_BOARD_TO_IMAGE_1" FOREIGN KEY (
    "BOARD_NO"
)
REFERENCES "BOARD" (
    "BOARD_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_PAY_OPTION_TO_PAYMENT_1" FOREIGN KEY (
    "PAY_OPTION_NO"
)
REFERENCES "PAY_OPTION" (
    "PAY_OPTION_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_RESERVATION_TO_PAYMENT_1" FOREIGN KEY (
    "RESERVATION_NO"
)
REFERENCES "RESERVATION" (
    "RESERVATION_NO"
);

ALTER TABLE "SELF_CHECK_QUESTION" ADD CONSTRAINT "FK_SELF_CHECK_CATEGORY_TO_SELF_CHECK_QUESTION_1" FOREIGN KEY (
    "CATEGORY_NO"
)
REFERENCES "SELF_CHECK_CATEGORY" (
    "CATEGORY_NO"
);

ALTER TABLE "SELF_CHECK_ANSWER" ADD CONSTRAINT "FK_SELF_CHECK_QUESTION_TO_SELF_CHECK_ANSWER_1" FOREIGN KEY (
    "QUESTION_NO"
)
REFERENCES "SELF_CHECK_QUESTION" (
    "QUESTION_NO"
);

ALTER TABLE "SELF_CHECK_ANSWER" ADD CONSTRAINT "FK_SELF_CHECK_QUESTION_TO_SELF_CHECK_ANSWER_2" FOREIGN KEY (
    "CATEGORY_NO"
)
REFERENCES "SELF_CHECK_QUESTION" (
    "CATEGORY_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_BOARD_TO_NOTICE_1" FOREIGN KEY (
    "BOARD_NO"
)
REFERENCES "BOARD" (
    "BOARD_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_LETTER_TO_NOTICE_1" FOREIGN KEY (
    "LETTER_NO"
)
REFERENCES "LETTER" (
    "LETTER_NO"
);

ALTER TABLE "SELF_CHECK_RESULT" ADD CONSTRAINT "FK_SELF_CHECK_CATEGORY_TO_SELF_CHECK_RESULT_1" FOREIGN KEY (
    "CATEGORY_NO"
)
REFERENCES "SELF_CHECK_CATEGORY" (
    "CATEGORY_NO"
);

ALTER TABLE "PROFESSION_HOSPITAL" ADD CONSTRAINT "FK_PROFESSION_TO_PROFESSION_HOSPITAL_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "PROFESSION_INFORMATION" ADD CONSTRAINT "FK_PROFESSION_TO_PROFESSION_INFORMATION_1" FOREIGN KEY (
    "PROFESSION_NO"
)
REFERENCES "PROFESSION" (
    "PROFESSION_NO"
);

ALTER TABLE "MEMBER_SELF_CHECK" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_SELF_CHECK_1" FOREIGN KEY (
    "MEMBER_NO"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "MEMBER_SELF_CHECK" ADD CONSTRAINT "FK_SELF_CHECK_RESULT_TO_MEMBER_SELF_CHECK_1" FOREIGN KEY (
    "RESULT_NO"
)
REFERENCES "SELF_CHECK_RESULT" (
    "RESULT_NO"
);

ALTER TABLE "MEMBER_SELF_CHECK" ADD CONSTRAINT "FK_SELF_CHECK_RESULT_TO_MEMBER_SELF_CHECK_2" FOREIGN KEY (
    "CATEGORY_NO"
)
REFERENCES "SELF_CHECK_RESULT" (
    "CATEGORY_NO"
);

ALTER TABLE "MANAGER" ADD CONSTRAINT "FK_MANAGER_GRADE_TO_MANAGER_1" FOREIGN KEY (
    "GRADE_NO2"
)
REFERENCES "MANAGER_GRADE" (
    "GRADE_NO"
);

ALTER TABLE "RESERVATION_PAYMENT" ADD CONSTRAINT "FK_PAYMENT_TO_RESERVATION_PAYMENT_1" FOREIGN KEY (
    "PAY_NO"
)
REFERENCES "PAYMENT" (
    "PAY_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "FK_CHATTING_TO_CHATTING_MESSAGE_1" FOREIGN KEY (
    "CHATTING_NO"
)
REFERENCES "CHATTING" (
    "CHATTING_NO"
);

ALTER TABLE "CHAT_FILE" ADD CONSTRAINT "FK_CHATTING_TO_CHAT_FILE_1" FOREIGN KEY (
    "CHATTING_NO"
)
REFERENCES "CHATTING" (
    "CHATTING_NO"
);



---------------------------------------------------------------------------------
-- 채팅 메시지
CREATE SEQUENCE SEQ_CM_NO;

-- 조용진 -- 조용진 -- 조용진 -- 조용진 -- 조용진 -- 조용진 -- 조용진 -- 조용진 -- 조용진 -- 조용진
ALTER TABLE PROFESSION ADD FOREIGN KEY(STATUS_CD) REFERENCES STATUS(STATUS_CD);

-- DB가 너무 어렵다
SELECT PROFESSION_NO, PROFESSION_NM, PROFESSION_PHONE, PROFESSION_MAJOR,
       PRO_INTRO, PRO_STORY, PRO_CARRER, PRO_TAG,
       LISTAGG(COUNSEL_CATEGORY_NO,',') WITHIN GROUP(ORDER BY PROFESSION_NO) AS COUNSEL_CATEGORY_NO,
    LISTAGG(COUNSEL_PRICE,',') WITHIN GROUP(ORDER BY PROFESSION_NO) AS COUNSEL_PRICE
FROM PROFESSION_PRICE
    JOIN PROFESSION USING(PROFESSION_NO)
    JOIN PROFESSION_INFORMATION USING(PROFESSION_NO)
WHERE PROFESSION_NO IN (SELECT PROFESSION_NO FROM PROFESSION_INFORMATION
    WHERE (PRO_TAG LIKE '%1001%'))
GROUP BY PROFESSION_NO, PROFESSION_NM, PROFESSION_PHONE, PROFESSION_MAJOR, PRO_INTRO,
    PRO_STORY, PRO_CARRER, PRO_TAG;


-- 제약조건 삭제
--ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
ALTER TABLE PROFESSION DROP CONSTRAINT 제약조건명;

-- PK 제약조건 추가
ALTER TABLE STATUS ADD PRIMARY KEY (STATUS_CD);

CREATE SEQUENCE SEQ_PROFESSION_NO;

-- 전문가 등록
INSERT INTO PROFESSION VALUES(
SEQ_PROFESSION_NO.NEXTVAL, 'user05', 'pass05!', '유저5', '010-1111-2222',
DEFAULT, '남', '999999', '등록완료', 4);
COMMIT;

-- 전문가 병원
INSERT INTO PROFESSION_HOSPITAL VALUES(
6, '365 열린내과의원', '서울 노원구 한글비석로 77 한성여객빌딩 3층', '010-0000-0000', '02-000-0000');
COMMIT;

-- 전문가 정보
INSERT INTO PROFESSION_INFORMATION VALUES(
6, '서울대학교연건캠퍼스', '의예과', '심리상담');
COMMIT;

SELECT * FROM PROFESSION_HOSPITAL;


ALTER TABLE CHATTING_MESSAGE MODIFY PROFESSION_NO NULL;
ALTER TABLE CHATTING_MESSAGE MODIFY MEMBER_NO NULL;

ALTER TABLE MEMBER MODIFY MEMBER_PHONE NULL;

ALTER TABLE MEMBER MODIFY MEMBER_PW VARCHAR2(100);

-- 카카오 로그인
INSERT INTO MEMBER VALUES(
    SEQ_MEMBER_NO.NEXTVAL, NULL, NULL, NULL, NULL,
    '닉네임', NULL, '남', DEFAULT, 'KAKAO', DEFAULT);


----------------------------------테이블 변경
DROP TABLE "EMOTION_DIARY";

CREATE TABLE "EMOTION_DIARY" (
	"EMOTION_NO"	NUMBER		NOT NULL,
	"EMOTION_ARRAY"	VARCHAR2(300)		NOT NULL,
	"STRESS_ARRAY"	VARCHAR2(300)		NOT NULL,
	"EMOTION_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"STRESS_AGREE"	NUMBER	DEFAULT 0	NOT NULL,
	"DIARY_AGREE"	NUMBER	DEFAULT 0	NOT NULL,
	"EMOTION_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"EMOTION_UD"	DATE		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_NO" IS '증상기록 번호';

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_ARRAY" IS '증상기록 json';

COMMENT ON COLUMN "EMOTION_DIARY"."STRESS_ARRAY" IS '스트레스 array';

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_CONTENT" IS '증상기록 메모';

COMMENT ON COLUMN "EMOTION_DIARY"."STRESS_AGREE" IS '스트레스 동의';

COMMENT ON COLUMN "EMOTION_DIARY"."DIARY_AGREE" IS '메모 동의';

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_DT" IS '증상 기록 시간';

COMMENT ON COLUMN "EMOTION_DIARY"."EMOTION_UD" IS '수정 시간';

COMMENT ON COLUMN "EMOTION_DIARY"."MEMBER_NO" IS '회원 번호';

ALTER TABLE "EMOTION_DIARY" ADD CONSTRAINT "PK_EMOTION_DIARY" PRIMARY KEY (
	"EMOTION_NO"
);

CREATE SEQUENCE SEQ_EMOTION_DIARY_NO;














